package ocpp;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyFactory;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.cert.Certificate;
import java.security.cert.CertificateFactory;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import javax.net.ssl.KeyManagerFactory;

/** The charger fleet generated by the provision tool (chargers.csv + client certificates). */
final class Fleet {

    record Charger(String id, String ocppVersion, int securityProfile, String password) {

        /** WebSocket subprotocol offered at connect time. */
        String subprotocol() {
            return "ocpp" + ocppVersion;
        }

        String url(Config cfg) {
            return securityProfile == 1
                    ? "ws://" + cfg.host + ":" + cfg.wsPort + "/ocpp/" + cfg.vhost + "/" + id
                    : "wss://" + cfg.host + ":" + cfg.wssPort + "/ocpp/" + cfg.vhost + "/" + id;
        }

        /** HTTP Basic auth for profiles 1 and 2; profile 3 authenticates with its certificate. */
        String authorization() {
            return "Basic " + Base64.getEncoder()
                    .encodeToString((id + ":" + password).getBytes(StandardCharsets.UTF_8));
        }
    }

    private static final char[] KEYSTORE_PASSWORD = "changeit".toCharArray();

    private final List<Charger> chargers;
    private final Path clientCertDir;

    Fleet(Path dataDir, int limit) throws IOException {
        List<Charger> all = new ArrayList<>();
        List<String> lines = Files.readAllLines(dataDir.resolve("chargers.csv"));
        for (String line : lines.subList(1, lines.size())) {
            String[] f = line.split(",", -1);
            all.add(new Charger(f[0], f[1], Integer.parseInt(f[2]), f[3]));
        }
        this.chargers = limit > 0 && limit < all.size() ? all.subList(0, limit) : all;
        this.clientCertDir = dataDir.resolve("pki").resolve("clients");
    }

    int size() {
        return chargers.size();
    }

    Charger get(int index) {
        return chargers.get(index);
    }

    /**
     * Gatling assigns user ids 1, 2, 3... in injection order. Chargers are injected before any
     * other scenario starts, so user {@code n} simulates the {@code n}-th charger, both for its
     * session data and for the TLS client certificate chosen when the user starts.
     */
    Charger forUser(long userId) {
        return chargers.get((int) ((userId - 1) % chargers.size()));
    }

    /** Key material for a virtual user: the charger's certificate on Security Profile 3, else none. */
    KeyManagerFactory keyManagers(long userId) {
        try {
            KeyStore store = KeyStore.getInstance("PKCS12");
            store.load(null, null);
            if (userId >= 1 && userId <= chargers.size()) {
                Charger charger = forUser(userId);
                if (charger.securityProfile() == 3) {
                    store.setKeyEntry("client", readKey(clientCertDir.resolve(charger.id() + ".key")),
                            KEYSTORE_PASSWORD, new Certificate[] {readCert(clientCertDir.resolve(charger.id() + ".crt"))});
                }
            }
            KeyManagerFactory factory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            factory.init(store, KEYSTORE_PASSWORD);
            return factory;
        } catch (Exception e) {
            throw new IllegalStateException("Cannot load client certificate for user " + userId, e);
        }
    }

    private static PrivateKey readKey(Path path) throws Exception {
        String pem = Files.readString(path)
                .replace("-----BEGIN PRIVATE KEY-----", "")
                .replace("-----END PRIVATE KEY-----", "")
                .replaceAll("\\s", "");
        return KeyFactory.getInstance("EC").generatePrivate(new PKCS8EncodedKeySpec(Base64.getDecoder().decode(pem)));
    }

    private static Certificate readCert(Path path) throws Exception {
        try (var in = Files.newInputStream(path)) {
            return CertificateFactory.getInstance("X.509").generateCertificate(in);
        }
    }
}
